
_articles:
    path:     /articles
    defaults: { _controller: GeekhubGeekBundle:Articles:show }

_article:
    path:     /article/{id}
    defaults: { _controller: GeekhubGeekBundle:Article:show }

_createArticle:
    path:     /create/article
    defaults: { _controller: GeekhubGeekBundle:Article:create }

_editArticle:
    path:     /article/{id}/edit
    defaults: { _controller: GeekhubGeekBundle:Article:update}

_deleteArticle:
    path:     /article/{id}/delete
    defaults: { _controller: GeekhubGeekBundle:Article:delete}
